export const projects = [
  {
    id: 1,
    image: "/images/janela.png",
    category: "janelas",
    title: "Proteção para Janela",
    location: "Mooca - SP",
  },
  {
    id: 2,
    image: "/images/sacada.png",
    category: "sacadas",
    title: "Rede para Sacada",
    location: "Tatuapé - SP",
  },
  {
    id: 3,
    image: "/images/gato.png",
    category: "externo",
    title: "Proteção para Área Externa",
    location: "Vila Madalena - SP",
  },
  {
    id: 4,
    image: "/images/janela2.png",
    category: "janelas",
    title: "Janela Residencial",
    location: "Perdizes - SP",
  },
  {
    id: 5,
    image: "/images/sacada2.png",
    category: "sacadas",
    title: "Sacada com Vista",
    location: "Morumbi - SP",
  },
  {
    id: 6,
    image: "/images/varanda.png",
    category: "sacadas",
    title: "Varanda Gourmet",
    location: "Itaim Bibi - SP",
  },
  {
    id: 7,
    image: "/images/quarto.png",
    category: "janelas",
    title: "Quarto Infantil",
    location: "Vila Alpina - SP",
  },
  {
    id: 8,
    image: "/images/teste.png",
    category: "janelas",
    title: "Segurança na sua Janela",
    location: "Santo André - SP",
  },
  {
    id: 9,
    image: "/images/cama01.jpg",
    category: "cama",
    title: "Proteção para sua Cama",
    location: "São Paulo - SP",
  },
  {
    id: 10,
    image: "/images/cama02.jpg",
    category: "cama",
    title: "Proteção para sua Cama",
    location: "São Paulo - SP",
  },
  {
    id: 11,
    image: "/images/externo01.jpg",
    category: "externo",
    title: "Segurança Externa",
    location: "São Paulo - SP",
  },
  {
    id: 12,
    image: "/images/externo02.jpg",
    category: "externo",
    title: "Segurança Externa",
    location: "São Paulo - SP",
  },
  {
    id: 13,
    image: "/images/externo03.jpg",
    category: "externo",
    title: "Segurança Externa",
    location: "São Paulo - SP",
  },
  {
    id: 14,
    image: "/images/externo04.jpg",
    category: "externo",
    title: "Segurança Externa",
    location: "São Paulo - SP",
  },
  {
    id: 15,
    image: "/images/externo05.jpg",
    category: "externo",
    title: "Segurança Externa",
    location: "São Paulo - SP",
  },
  {
    id: 16,
    image: "/images/janela01.jpg",
    category: "janelas",
    title: "Segurança na sua Janela",
    location: "São Paulo - SP",
  },
  {
    id: 17,
    image: "/images/janela02.jpg",
    category: "janelas",
    title: "Segurança na sua Janela",
    location: "São Paulo - SP",
  },
  {
    id: 18,
    image: "/images/janela03.jpg",
    category: "janelas",
    title: "Segurança na sua Janela",
    location: "São Paulo - SP",
  },
  {
    id: 19,
    image: "/images/sacada03.jpg",
    category: "sacadas",
    title: "Proteção para sua Sacada",
    location: "São Paulo - SP",
  },
  {
    id: 20,
    image: "/images/sacada04.jpg",
    category: "sacadas",
    title: "Proteção para sua Sacada",
    location: "São Paulo - SP",
  },
  {
    id: 21,
    image: "/images/sacada05.jpg",
    category: "sacadas",
    title: "Proteção para sua Sacada",
    location: "São Paulo - SP",
  },
  {
    id: 22,
    image: "/images/sacada06.jpg",
    category: "sacadas",
    title: "Proteção para sua Sacada",
    location: "São Paulo - SP",
  },
  {
    id: 23,
    image: "/images/sacada07.jpg",
    category: "sacadas",
    title: "Proteção para sua Sacada",
    location: "São Paulo - SP",
  },
];

export const categories = [
  { id: "all", name: "Todos", count: projects.length },
  {
    id: "janelas",
    name: "Janelas",
    count: projects.filter((p) => p.category === "janelas").length,
  },
  {
    id: "sacadas",
    name: "Sacadas",
    count: projects.filter((p) => p.category === "sacadas").length,
  },
  {
    id: "externo",
    name: "Externo",
    count: projects.filter((p) => p.category === "externo").length,
  },
  {
    id: "cama",
    name: "Cama",
    count: projects.filter((p) => p.category === "cama").length,
  },
];
